# samples
device: cpu  # cpu or 0, 1, 2, 3 ...
    
input:
    sample:
        min_shape: [1, 9, 32, 32]
        max_shape: [4, 9, 64, 64]
        use_shape: [1, 9, 64, 64]
    timestep: 
        min_shape: [1]
        max_shape: [1]
        use_shape: [1]
    encoder_hidden_states:
        min_shape: [1, 77, 1024]
        max_shape: [4, 77, 1024]
        use_shape: [1, 77, 1024]

output:
    out_sample:
        use_shape: [1, 4, 64, 64]